export type InterviewMode = 'short' | 'medium' | 'long' | 'freestyle';

export interface CategorizedSkill {
  skill: string;
  category: string;
  score?: number;
  question_script?: string; // <--- NEW: The generated scenario/question
}

export interface GeminiAnalysisResult {
  matches: CategorizedSkill[];
  gaps: CategorizedSkill[];
  cool_skills: CategorizedSkill[];
  transferable_skills: CategorizedSkill[];
  soft_skills: CategorizedSkill[]; // <--- Changed from string[] to Object
  job_role?: string;
}

export interface InterviewTopic {
  id: string;
  type: 'Match' | 'Gap' | 'SoftSkill' | 'CoolSkill' | 'Intro' | 'Outro';
  topic: string;
  category?: string; // Added for grouping
  context: string; // This field will now store the DEEP SCENARIO generated by Pro
  estimated_time: string;
  score?: number; // Added Relevance Score
}

export interface InterviewPlan {
  meta: {
    mode: InterviewMode;
    total_estimated_time: string;
    isInfinite?: boolean;
    new_question_ids?: string[];
  };
  queue: InterviewTopic[];
}

export interface EvaluationMetrics {
  accuracy: number;
  depth: number;
  structure: number;
  reasoning: string;
}

// ============================================
// ENHANCED EVALUATION SYSTEM TYPES
// ============================================

/**
 * QualityLevel: Semantic representation of answer quality.
 * Maps compositeScore to human-readable levels for decision-making.
 * 
 * Score Mapping:
 * - excellent: 9.0-10.0 (expert-level, specific examples, deep understanding)
 * - good: 7.0-8.9 (solid practical experience, correct terminology)
 * - mediocre: 5.0-6.9 (textbook understanding, lacks real-world depth)
 * - poor: 3.0-4.9 (weak/confused understanding, vague)
 * - fail: 0.0-2.9 (fundamentally wrong but attempting)
 */
export type QualityLevel = 'excellent' | 'good' | 'mediocre' | 'poor' | 'fail';

/**
 * AnswerIssue: Specific problems identified in the candidate's answer.
 * Used to provide targeted feedback and help Victoria guide the conversation.
 */
export type AnswerIssue =
  | 'NO_EXAMPLE'        // Didn't provide concrete example
  | 'WRONG_CONCEPT'     // Fundamental misunderstanding
  | 'TOO_VAGUE'         // Answer lacks specificity
  | 'OFF_TOPIC'         // Didn't answer the question asked
  | 'RAMBLING'          // Unfocused, jumping between ideas
  | 'INCOMPLETE'        // Started well but didn't finish thought
  | 'SHALLOW';          // Surface-level, no depth

/**
 * UserIntent: Extended intent types for more granular classification.
 * Separates quality attempts (STRONG_ATTEMPT vs WEAK_ATTEMPT) from actions.
 * 
 * Intent Behavior:
 * - STRONG_ATTEMPT: Good quality attempt (compositeScore >= 5) → normal flow
 * - WEAK_ATTEMPT: Poor quality attempt (compositeScore < 5) → patience increases
 * - CLARIFICATION: Request for rephrasing → metrics zeroed, stay on topic
 * - GIVE_UP: Admit not knowing → move to next topic, slight patience
 * - SHOW_ANSWER: Request explanation → educational transition
 * - NONSENSE: Off-topic trolling → triggers anger increase
 * - READY_CONFIRM: User says "ready" → intro phase only
 */
export type UserIntent =
  | 'STRONG_ATTEMPT'    // Good quality attempt (score >= 5)
  | 'WEAK_ATTEMPT'      // Poor quality attempt (score < 5)
  | 'CLARIFICATION'     // Asking for question to be rephrased
  | 'GIVE_UP'           // Admitting don't know, skip
  | 'SHOW_ANSWER'       // Request to reveal correct answer
  | 'NONSENSE'          // Off-topic trolling
  | 'READY_CONFIRM';    // User says "ready" (intro only)

/**
 * AnalysisResponse: Enhanced evaluation result with multi-dimensional analysis.
 * 
 * Key improvements over previous version:
 * - compositeScore: Weighted average for decision-making
 * - level: Semantic quality level for human-readable feedback
 * - issues: Specific problems for targeted feedback
 * - suggestedFeedback: Pre-generated phrase for Victoria's voice
 */
export interface AnalysisResponse {
  // Keep existing metrics for transparency and detailed logging
  metrics: EvaluationMetrics;

  // NEW: Composite score (weighted based on question type)
  // Technical: accuracy×0.5 + depth×0.3 + structure×0.2
  // SoftSkill: accuracy×0.3 + depth×0.3 + structure×0.4
  // Intro: accuracy×0.2 + depth×0.2 + structure×0.6
  compositeScore: number;  // 0-10, calculated by combining metrics

  // NEW: Semantic quality level
  level: QualityLevel;

  // NEW: Specific problems identified
  issues: AnswerIssue[];

  // Intent classification using extended types
  intent: UserIntent;

  // NEW: Suggested feedback snippet for Victoria
  // Short phrase (5-10 words) that Victoria should incorporate naturally
  suggestedFeedback: string;
}

export interface VoiceGenerationContext {
  currentTopic: InterviewTopic;
  nextTopic: InterviewTopic | null;
  transitionMode: 'STAY' | 'NEXT_FAIL' | 'NEXT_PASS' | 'NEXT_EXPLAIN' | 'FINISH_INTERVIEW' | 'TERMINATE_ANGER';
  angerLevel?: number;           // Added for final feedback
  engagementLevel?: number;      // NEW: Engagement metric (0-100)
  vibe?: VibeConfig;             // NEW: Current emotional state
}

export interface AiResponse {
  message: string;
  metrics: EvaluationMetrics;
}

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: number;
}

export interface InterviewContext {
  currentTopic: InterviewTopic;
  previousResult: string | null;
  angerLevel: number;
  isLastTopic: boolean;
}

export interface QuestionResult {
  topic: string;
  userAnswer: string;
  score: number; // 0-10
  feedback: string;
  detailedFeedback?: string; // ✨ NEW: Comprehensive 4-6 sentence feedback with actionable advice
  advice?: string; // ✨ NEW: Generated study advice (2-3 sentences)
  metrics?: EvaluationMetrics; // Optional for backward compatibility
  compositeScore?: number; // NEW: Weighted average (0-10)
  level?: QualityLevel; // NEW: Semantic quality level
  issues?: AnswerIssue[]; // NEW: Specific problems identified
  intent?: UserIntent; // NEW: User's intent classification
  suggestedFeedback?: string; // NEW: Short phrase for Victoria (5-10 words)
  rawExchange?: Array<{ // ✨ NEW: Raw Q&A for debug section
    speaker: 'Victoria' | 'User';
    text: string;
    timestamp?: number;
  }>;
}

export interface FinalInterviewReport {
  questions: QuestionResult[];
  averageScore: number;
  overallSummary: string;
  timestamp: number;
  wasForceFinished?: boolean; // ✨ NEW: True if manually force-finished via shake menu
  terminationReason?: 'completed' | 'force_finished' | 'anger_limit' | 'patience_limit'; // ✨ NEW: How interview ended
}

// ============================================
// EMOTION & VIBE SYSTEM TYPES
// ============================================

/**
 * CartesiaEmotion: Emotion values supported by Cartesia API
 * Reference: https://docs.cartesia.ai/api-reference/tts/bytes
 */
export type CartesiaEmotion =
  | 'neutral'
  | 'positivity:lowest'
  | 'positivity:low'
  | 'positivity:high'
  | 'positivity:highest'
  | 'anger:lowest'
  | 'anger:low'
  | 'anger:high'
  | 'anger:highest'
  | 'sadness:lowest'
  | 'sadness:low'
  | 'sadness:high'
  | 'sadness:highest'
  | 'surprise:lowest'
  | 'surprise:low'
  | 'surprise:high'
  | 'surprise:highest'
  | 'curiosity:lowest'
  | 'curiosity:low'
  | 'curiosity:high'
  | 'curiosity:highest';

/**
 * VibeLabel: 15 emotional states for Victoria based on anger/engagement
 */
export type VibeLabel =
  // Positive vibes (low anger, high engagement)
  | 'Impressed'       // anger 0-10, engagement 80-100
  | 'Encouraging'     // anger 0-10, engagement 50-79
  | 'Professional'    // anger 11-25, engagement 60-100

  // Neutral vibes (medium anger, varying engagement)
  | 'Neutral'         // anger 11-25, engagement 30-59
  | 'Curious'         // anger 26-40, engagement 60-100
  | 'Concerned'       // anger 26-40, engagement 30-59

  // Negative mild (medium anger, low engagement or special cases)
  | 'Disappointed'    // anger 26-40, engagement 0-29
  | 'Skeptical'       // anger 41-60, engagement 40-100
  | 'Amused'          // anger 41-60, absurd error detected

  // Negative strong (high anger)
  | 'Irritated'       // anger 41-60, engagement 0-39
  | 'Frustrated'      // anger 61-70
  | 'Hostile'         // anger 71-85
  | 'Dismissive'      // anger 86-90
  | 'Furious';        // anger 91-100

/**
 * VibeConfig: Complete configuration for an emotional state
 */
export interface VibeConfig {
  label: VibeLabel;
  cartesiaEmotion: CartesiaEmotion;
  speed: number;                    // Speech rate (0.5 - 1.5)
  emotionLevel?: string[];          // Cartesia emotion array format
  promptModifier: string;           // Instructions for Gemini voice generation
  description: string;              // Human-readable explanation
}

/**
 * CartesiaTTSRequest: Cartesia API request structure
 * Reference: https://docs.cartesia.ai/api-reference/tts/bytes
 */
export interface CartesiaTTSRequest {
  model_id: string;                 // 'sonic-english'
  transcript: string;               // Text to speak (NOT "text")
  voice: {
    mode: 'id';
    id: string;
    __experimental_controls?: {
      speed?: string;               // 'slowest' | 'slow' | 'normal' | 'fast' | 'fastest'
      emotion?: string[];           // Array of emotion strings
    };
  };
  output_format: {
    container: 'mp3' | 'wav';
    encoding: 'mp3' | 'pcm_s16le' | 'pcm_f32le' | 'pcm_mulaw';
    sample_rate: number;
  };
}

// ============================================
// TTS PROVIDER TYPES
// ============================================

/**
 * TTSProvider: Text-to-Speech provider selection
 */
export type TTSProvider = 'cartesia' | 'openai';

/**
 * OpenAIVoice: Available voices for OpenAI TTS
 */
export type OpenAIVoice = 
  | 'alloy'   // Сбалансированный мужской/женский
  | 'echo'    // Мужской, мягкий
  | 'fable'   // Мужской, британский
  | 'onyx'    // Мужской, глубокий
  | 'nova'    // Женский, дружелюбный
  | 'shimmer'; // Женский, мягкий
