export type InterviewMode = 'short' | 'medium' | 'long' | 'freestyle';

export interface CategorizedSkill {
  skill: string;
  category: string;
  score?: number;
  question_script?: string; // <--- NEW: The generated scenario/question
}

export interface GeminiAnalysisResult {
  matches: CategorizedSkill[];
  gaps: CategorizedSkill[];
  cool_skills: CategorizedSkill[];
  transferable_skills: CategorizedSkill[];
  soft_skills: CategorizedSkill[]; // <--- Changed from string[] to Object
  job_role?: string;
}

export interface InterviewTopic {
  id: string;
  type: 'Match' | 'Gap' | 'SoftSkill' | 'CoolSkill' | 'Intro' | 'Outro';
  topic: string;
  category?: string; // Added for grouping
  context: string; // This field will now store the DEEP SCENARIO generated by Pro
  estimated_time: string;
  score?: number; // Added Relevance Score
}

export interface InterviewPlan {
  meta: {
    mode: InterviewMode;
    total_estimated_time: string;
    isInfinite?: boolean;
    new_question_ids?: string[];
  };
  queue: InterviewTopic[];
}

export interface EvaluationMetrics {
    accuracy: number;
    depth: number;
    structure: number;
    reasoning: string;
}

export interface AnalysisResponse {
    metrics: EvaluationMetrics;
    intent: 'ATTEMPT' | 'GIVE_UP' | 'CLARIFICATION' | 'SHOW_ANSWER' | 'NONSENSE';
}

export interface VoiceGenerationContext {
    currentTopic: InterviewTopic;
    nextTopic: InterviewTopic | null;
    transitionMode: 'STAY' | 'NEXT_FAIL' | 'NEXT_PASS' | 'NEXT_EXPLAIN' | 'FINISH_INTERVIEW' | 'TERMINATE_ANGER';
    angerLevel?: number; // Added for final feedback
}

export interface AiResponse {
    message: string;
    metrics: EvaluationMetrics;
}

export interface ChatMessage {
    role: 'user' | 'assistant' | 'system';
    content: string;
}

export interface InterviewContext {
    currentTopic: InterviewTopic;
    previousResult: string | null;
    angerLevel: number;
    isLastTopic: boolean;
}

export interface QuestionResult {
  topic: string;
  userAnswer: string;
  score: number; // 0-10
  feedback: string;
}

export interface FinalInterviewReport {
  questions: QuestionResult[];
  averageScore: number;
  overallSummary: string;
  timestamp: number;
}
